# Generated by Django 4.1 on 2022-08-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
