# Generated by Django 4.1 on 2022-08-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_cliente_usuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='domiciliario',
        ),
    ]
