# Generated by Django 4.1 on 2022-08-30 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_envio_domiciliario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='pedido',
        ),
    ]
