# Generated by Django 4.1 on 2022-08-30 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_envio_cliente_remove_envio_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cliente'),
        ),
        migrations.AddField(
            model_name='envio',
            name='direccion',
            field=models.CharField(default='para llevar', max_length=200),
        ),
        migrations.AddField(
            model_name='envio',
            name='domiciliario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.domiciliario'),
        ),
        migrations.AddField(
            model_name='envio',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=200),
        ),
        migrations.AddField(
            model_name='envio',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.pedido'),
        ),
        migrations.AddField(
            model_name='envio',
            name='telefono',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='envio',
            name='valor_domi',
            field=models.IntegerField(default=0),
        ),
    ]
