# Generated by Django 4.1 on 2022-08-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_envio_cliente_envio_direccion_envio_domiciliario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tomado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
